name: Platformer Generated worked-fix Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on:
      - ubuntu-latest
    env:
      SERVICE_NAME: ebonynon/cicd-test-two
      CONTAINER_REGISTRY: https://index.docker.io/v1/
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        id: event-version
        run: echo ::set-output
          name=SOURCE_TAG::${GITHUB_REF#refs/heads/}-${{github.sha}}
      - name: Login to Docker Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME_84812236_E81E_4E39_B9A0_AD9256FA36A4 }}
          password: ${{ secrets.DOCKER_PASSWORD_84812236_E81E_4E39_B9A0_AD9256FA36A4 }}
      - name: Build the Docker image
        run: docker build --tag
          ${SERVICE_NAME}:${{steps.event-version.outputs.SOURCE_TAG }} --file
          Dockerfile .
      - name: Docker Push
        run: docker push $SERVICE_NAME:${{steps.event-version.outputs.SOURCE_TAG }}
      - name: Platformer Deploy
        uses: platformer-com/build-deploy-action@v1
        with:
          org-id: ${{secrets.ORG_ID_7FFC24BE_901E_46F6_A579_51F94389C135}}
          project-id: ${{secrets.PROJECT_ID_7FFC24BE_901E_46F6_A579_51F94389C135}}
          token: ${{secrets.AUTOGENERATED_CICD_7FFC24BE_901E_46F6_A579_51F94389C135}}
          image-name: ${{env.SERVICE_NAME}}
          tag: ${{steps.event-version.outputs.SOURCE_TAG }}
          container-id: 60f7883c-7263-4911-97c5-b78897bb582c
